### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by AndrewIsh** [PTFS-Europe/rebus-docs#2]
Clicking on search results doesn't work, they always end up with a 404. I think it has something to do with the URLs it's generating:

http://rebuslist.readthedocs.io/en/latest/manage_hierarchy.rst.html?highlight=rollover

Pretty sure that should be:

http://rebuslist.readthedocs.io/en/latest/manage_hierarchy.html?highlight=rollover

**Comment by mrenvoize** [comment]
https://github.com/rtfd/readthedocs.org/issues/2708

**Comment by AndrewIsh** [comment]
This now appears to be fixed upstream
